name: rgenerator
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - camelot-py
  - matplotlib
  - numpy
  - pandas
  - pillow
  - requests
  - tqdm
  - xlrd
  - fastapi
  - uvicorn
  - pip
  - pytest
  - pytest-cov
  - miktex
  - git
  - streamlit
  - ipykernel
  - pip:
      - openpyxl
      - pymupdf
      - docxtpl
      - docx2pdf
      # Aqui deber√≠a instalarse rgenerator de alguna forma
      # ####
      # Lo siguiente viene solo para la rama main, en caso de devtest
      # instalar manualmente
      #- git+https://github.com/username/rgenerator.git