name: rgenerator
channels:
  - conda-forge
  - defaults

dependencies:
  - camelot-py   
  - matplotlib
  - numpy
  - pandas
  - pillow
  - requests
  - tqdm
  - xlrd
  - pip
  - pip:
      - openpyxl
      - fitz