name: rgenerator
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - camelot-py
  - matplotlib
  - numpy
  - pandas
  - pillow
  - requests
  - tqdm
  - xlrd
  - pip
  - pytest
  - pytest-cov
  - tomllib
  - pip:
      - openpyxl
      - pymupdf